[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.2.0" }
selene = { github = "Kampfkarren/selene", version = "0.20.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=0.14.2" }
luau-lsp = { github = "johnnymorganz/luau-lsp", version = "=1.23.0"}
darklua = { github = "seaofvoices/darklua", version = "=0.12.1" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
